services:
  web:
    build: ./src/backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - ENV=development

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src/frontend:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network: